<a href="https://colab.research.google.com/github/KacperWardzala/data-science-bootcamp2023/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics

In [3]:
import numpy as np
np.__version__

'1.23.5'

In [ ]:
print(dir(np))

1D array

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([2.8, 3.1, 4.14, 8.9])
print(x)

[2.8  3.1  4.14 8.9 ]


2D array

In [ ]:
x = np.array([[7, 8], [-3, 5]])
x

array([[ 7,  8],
       [-3,  5]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[8, 9, 4], [45, 24, 1]])
print(x)

[[ 8  9  4]
 [45 24  1]]


In [ ]:
x.shape

(2, 3)

3D array

In [ ]:
x = np.array(
    [[[4, 2, 3],
      [5, 2, 5]],

      [[7, 7, 3],
      [1, 9, 6]],

     [[5, 3, 2],
      [2, 3, 1]]]
             )
print(x)

[[[4 2 3]
  [5 2 5]]

 [[7 7 3]
  [1 9 6]]

 [[5 3 2]
  [2 3 1]]]


In [ ]:
x.ndim

3

In [ ]:
x.shape

(3, 2, 3)



# Data types

In [ ]:
A = np.array([1, 2, 3])
A.dtype


dtype('int64')

In [ ]:
A = np.array([1.0, 2.3, 3.3])
A.dtype


dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype='float')
A.dtype


dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype


dtype('complex128')

In [ ]:
A = np.array([1.0, 2.3, 3.3], dtype='int')
A.dtype

array([1, 2, 3])

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

In [ ]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

# Making Arrays

In [ ]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones(shape=(5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full(shape=(3, 3), fill_value=7, dtype='int')

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.linspace(start=0, stop=1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Arrays Operations

In [9]:
A = np.array([3, 1, -4, 2])
B = np.array([9, 1, 3, -2])
print(A)
print(B)

[ 3  1 -4  2]
[ 9  1  3 -2]


In [10]:
A + B

array([12,  2, -1,  0])

In [11]:
A * B

array([ 27,   1, -12,  -4])

In [12]:
A / B

array([ 0.33333333,  1.        , -1.33333333, -1.        ])

In [13]:
A + 3

array([ 6,  4, -1,  5])

In [14]:
2 * A

array([ 6,  2, -8,  4])

With np funcions

In [15]:
np.add(A, B)

array([12,  2, -1,  0])

In [17]:
np.subtract(A, B)

array([-6,  0, -7,  4])

In [18]:
np.multiply(A, B)

array([ 27,   1, -12,  -4])

In [19]:
np.divide(A, B)

array([ 0.33333333,  1.        , -1.33333333, -1.        ])

In [22]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])

In [23]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [24]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [25]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [26]:
X @ Y

array([[  3,   6],
       [-12,   0]])

# Pseudorandom Numbers

In [27]:
np.random.seed(0)

Normal Distribution

In [28]:
np.random.randn()

1.764052345967664

In [29]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [30]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

Uniform Distribution

In [32]:
np.random.rand()

0.3687251706609641

In [33]:
np.random.rand(10)

array([0.82099323, 0.09710128, 0.83794491, 0.09609841, 0.97645947,
       0.4686512 , 0.97676109, 0.60484552, 0.73926358, 0.03918779])

In [35]:
np.random.rand(10, 3)

array([[0.59204193, 0.57225191, 0.22308163],
       [0.95274901, 0.44712538, 0.84640867],
       [0.69947928, 0.29743695, 0.81379782],
       [0.39650574, 0.8811032 , 0.58127287],
       [0.88173536, 0.69253159, 0.72525428],
       [0.50132438, 0.95608363, 0.6439902 ],
       [0.42385505, 0.60639321, 0.0191932 ],
       [0.30157482, 0.66017354, 0.29007761],
       [0.61801543, 0.4287687 , 0.13547406],
       [0.29828233, 0.56996491, 0.59087276]])

Random int

In [37]:
np.random.randint(10)

8

In [39]:
np.random.randint(low=10, high=101)

77

In [40]:
np.random.randint(low=10, high=101, size=10)

array([92, 13, 86, 45, 96, 71, 79, 97, 53, 42])

In [41]:
np.random.choice([4, 2, 1, 3, 5])

3

Shuffle arrays

In [42]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.random.shuffle(data)

In [45]:
data

array([1, 0, 7, 4, 6, 9, 8, 3, 2, 5])

# Basic Functions in the NumPy

In [46]:
np.exp(1)

2.718281828459045

In [47]:
np.sqrt(9)

3.0

In [51]:
np.all([2, 5, 1, 0])

False

In [53]:
np.any([1, 2, 1])

True

In [57]:
A = np.random.rand(5)
A

array([0.34535168, 0.92808129, 0.7044144 , 0.03183893, 0.16469416])

In [59]:
np.argmax(A)

1

In [61]:
A[np.argmax(A)]

0.9280812934655909

In [62]:
np.argmin(A)

3

In [63]:
np.argsort(A)

array([3, 4, 0, 2, 1])

In [64]:
np.max(A)

0.9280812934655909

In [65]:
np.min(A)

0.03183892953130785

In [66]:
np.mean(A)

0.43487609242304937

In [67]:
np.median(A)

0.3453516806969027

# Indexing and Slicing

In [69]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [70]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [71]:
A[:2]

array([0, 1])

In [72]:
A[[0, 2]]

array([0, 2])

In [73]:
A[-1]

19

In [77]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [78]:
A[0]

array([0, 1, 2, 3, 4])

In [79]:
A[:, 0]

array([ 0,  5, 10, 15])

In [80]:
A[1, 2]

7

In [82]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [84]:
 A[1, 2] = 14
 A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Iterating through arrays

In [85]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [86]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [87]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [88]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


# Reshaping arrays

In [93]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [89]:
A.shape

(4, 5)

In [90]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [91]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [92]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

# Boolean masks

In [95]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [96]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [97]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [100]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [101]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [102]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])