<a href="https://colab.research.google.com/github/KacperWardzala/data-science-bootcamp2023/blob/main/NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics

In [2]:
import numpy as np
np.__version__

'1.23.5'

In [ ]:
print(dir(np))

1D array

In [7]:
x = np.array([1, 3])
x

array([1, 3])

In [8]:
x.ndim

1

In [9]:
x.shape

(2,)

In [10]:
x.size

2

In [11]:
x.dtype

dtype('int64')

In [12]:
x = np.array([2.8, 3.1, 4.14, 8.9])
print(x)

[2.8  3.1  4.14 8.9 ]


2D array

In [15]:
x = np.array([[7, 8], [-3, 5]])
x

array([[ 7,  8],
       [-3,  5]])

In [16]:
x.ndim

2

In [17]:
x.shape

(2, 2)

In [18]:
x = np.array([[8, 9, 4], [45, 24, 1]])
print(x)

[[ 8  9  4]
 [45 24  1]]


In [19]:
x.shape

(2, 3)

3D array

In [28]:
x = np.array(
    [[[4, 2, 3],
      [5, 2, 5]],

      [[7, 7, 3],
      [1, 9, 6]],

     [[5, 3, 2],
      [2, 3, 1]]]
             )
print(x)

[[[4 2 3]
  [5 2 5]]

 [[7 7 3]
  [1 9 6]]

 [[5 3 2]
  [2 3 1]]]


In [29]:
x.ndim

3

In [30]:
x.shape

(3, 2, 3)



# Data types

In [31]:
A = np.array([1, 2, 3])
A.dtype


dtype('int64')

In [32]:
A = np.array([1.0, 2.3, 3.3])
A.dtype


dtype('float64')

In [34]:
A = np.array([1, 2, 3], dtype='float')
A.dtype


dtype('float64')

In [35]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype


dtype('complex128')

In [38]:
A = np.array([1.0, 2.3, 3.3], dtype='int')
A.dtype

array([1, 2, 3])

In [39]:
A

array([1, 2, 3])

In [40]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [42]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

In [43]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

# Making Tables

In [44]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
np.ones(shape=(5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
np.full(shape=(3, 3), fill_value=7, dtype='int')

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [48]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [51]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
np.linspace(start=0, stop=1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [55]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])